WakeApp/WakeApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wakeapp/', include('wake_app_homework.urls')),
]

WakeApp/wake_app_homework/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
app_name = "wake_app_homework"

urlpatterns = [
    #path('index/', views.IndexView.as_view(), name="index"),
    #path('index/', views.home, name='home'),
    path('index/', views.IndexView.as_view(), name="index"),
    path('route/add/', views.add_route, name="add-route"),

]

WakeApp/wake_app_homework/models.py
from django.db import models



class Route(models.Model):
    destination = models.CharField(max_length=512)
    home_address = models.CharField(max_length=512)
    route_length = models.TimeField()
    morning_routine = models.TimeField()
    classes_start = models.TimeField()
    wake_up_time = models.TimeField()

    class Meta:
        unique_together = ('destination', 'home_address',)

    def __str__(self):
        return f'{self.destination} to {self.home_address}'

WakeApp/wake_app_homework/forms.py
from django.forms import ModelForm, TimeField, \
    TimeInput


from .models import *

class RouteForm(ModelForm):
    route_length = TimeField(required=True, widget=TimeInput(attrs={'type': 'time'}))
    morning_routine = TimeField(required=True, widget=TimeInput(attrs={'type': 'time'}))
    classes_start = TimeField(required=True, widget=TimeInput(attrs={'type': 'time'}))
    class Meta:
         model = Route
         fields = ['destination', 'home_address', 'route_length',
                   'morning_routine', 'classes_start']

WakeApp/wake_app_homework/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
import datetime
from .models import *
from .forms import *
# Create your views here.





class IndexView(ListView):
    template_name = 'WakeApp/home.html'
    model = Route
    context_object_name = 'routes'
    extra_context = {
        'route_form': RouteForm(),
    }

def add_route(request):
    f = RouteForm(request.POST)
    if f.is_valid():
        print(type(f.cleaned_data['classes_start']))

        route_time = datetime.timedelta(hours=f.cleaned_data['route_length'].hour, minutes=f.cleaned_data['route_length'].minute)
        morning_routine_time = datetime.timedelta(hours=f.cleaned_data['morning_routine'].hour, minutes=f.cleaned_data['morning_routine'].minute)
        route_time_total = route_time + morning_routine_time
        time_to_wake_up = datetime.timedelta(hours=f.cleaned_data['classes_start'].hour, minutes=f.cleaned_data['classes_start'].minute) - route_time_total
        if route_time_total > time_to_wake_up:
            #show error here
            return HttpResponseRedirect(reverse('wake_app_homework:index'))
        print(type(time_to_wake_up))
        new_route = Route(
            destination = f.cleaned_data['destination'],
            home_address = f.cleaned_data['home_address'],
            route_length=f.cleaned_data['route_length'],
            morning_routine=f.cleaned_data['morning_routine'],
            classes_start=f.cleaned_data['classes_start'],
            wake_up_time=datetime.datetime.strptime(str(time_to_wake_up), "%H:%M:%S"),
        )
        #print(new_route)
    else:
        print(f.errors)
    new_route.save()
    #return render(request, "WakeApp/home.html")
    return HttpResponseRedirect(reverse('wake_app_homework:index'))

WakeApp/wake_app_homework/templates/WakeApp/home.html
{% extends 'based.html' %}
{% load crispy_forms_tags %}

{% block head %}
    <style>
    {
        box-sizing: border-box;
    }
    .column {
    float: left;
    width: 50%;
    }

    .row:after {
    content: "";
    display: table;
    clear: both;
    }
    </style>
{% endblock %}

{% block content %}
<div class="row">

<div class="column">
          <form method="post" action="{% url 'wake_app_homework:add-route'  %}">
              {% csrf_token %}
              {{ route_form|crispy }}
              <input type="submit" value="Add route">
          </form>
    <h3>{{ route }}</h3>
</div>

<div class="column">
      <select name="routes" id="routeSelect">
    {% for route in routes %}
        <option value={{ route.id }}>{{ route }}</option>
        <div id="welcomeDiv"  style="display:none;" class="answer_list" > {{ route }}</div>
    {% endfor %}
      </select>

    {% for route in routes %}
    <div id={{ route.id }} style="display:none;">
        <p>You should wake up at {{ route.wake_up_time }} o'clock</p>
    </div>
    {% endfor %}

    <script type="application/javascript">
        var prevValue;

        function showDiv() {
            if (prevValue !== "undefined" && document.getElementById(prevValue)) {
                document.getElementById(prevValue).style.display = "none";
            }
            var routeSelect = document.getElementById('routeSelect').value;
            prevValue = routeSelect;
            document.getElementById(routeSelect).style.display = "block";
        }
    </script>
    <br>
    <br>
    <input type="button" name="answer" value="Show Wake Up Time" onclick="showDiv()" />
</div>

    </div>
{% endblock %}

WakeApp/wake_app_homework/templates/based.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"  href="{%  static  'css/style.css'  %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/png">
    {% block head %}
    <title>Based</title>

    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-3">
                <a href="{% url 'wake_app_homework:index' %}"><img src="{% static 'img/favicon.png' %}"></a>
            </div>

        </div>
    {% block content %}

    {% endblock %}
    </div>

</body>
</html>